In [1]:
import pandas as pd

bioresponce = pd.read_csv('bioresponse.csv', header=0, sep=',')

FileNotFoundError: File b'bioresponse.csv' does not exist

In [2]:
cd "C:/Users/DimaN228/Documents"

C:\Users\DimaN228\Documents


In [3]:
bioresponce = pd.read_csv('bioresponse.csv', header=0, sep=',')

In [4]:
bioresponce.head()

Activity        D1        D2    D3   D4        D5        D6        D7  \
0         1  0.000000  0.497009  0.10  0.0  0.132956  0.678031  0.273166   
1         1  0.366667  0.606291  0.05  0.0  0.111209  0.803455  0.106105   
2         1  0.033300  0.480124  0.00  0.0  0.209791  0.610350  0.356453   
3         1  0.000000  0.538825  0.00  0.5  0.196344  0.724230  0.235606   
4         0  0.100000  0.517794  0.00  0.0  0.494734  0.781422  0.154361   

         D8        D9  ...    D1767  D1768  D1769  D1770  D1771  D1772  D1773  \
0  0.585445  0.743663  ...        0      0      0      0      0      0      0   
1  0.411754  0.836582  ...        1      1      1      1      0      1      0   
2  0.517720  0.679051  ...        0      0      0      0      0      0      0   
3  0.288764  0.805110  ...        0      0      0      0      0      0      0   
4  0.303809  0.812646  ...        0      0      0      0      0      0      0   

   D1774  D1775  D1776  
0      0      0      0  
1      0      1      0  
2      0      0      0  
3      0      0      0  
4      0      0      0  

[5 rows x 1777 columns]

In [5]:
print(bioresponce.shape)

(3751, 1777)


In [6]:
X = bioresponce.iloc[:, 1:]
y = bioresponce.Activity.values

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
X_train

D1        D2    D3    D4        D5        D6        D7        D8  \
994   0.133333  0.714512  0.20  0.25  0.162952  0.687409  0.176637  0.415709   
464   0.100000  0.614154  0.25  0.00  0.213374  0.603003  0.306633  0.328801   
3264  0.033300  0.539019  0.00  0.00  0.191258  0.612695  0.354226  0.557464   
2722  0.033300  0.553827  0.05  0.00  0.194294  0.702916  0.197505  0.371944   
3011  0.033300  0.664443  0.05  0.00  0.292082  0.640669  0.349088  0.490527   
2442  0.033300  0.558968  0.05  0.25  0.480125  0.731836  0.184690  0.067800   
1236  0.100000  0.611404  0.00  0.25  0.405778  0.728816  0.210367  0.067800   
3493  0.000000  0.451831  0.10  0.00  0.055000  0.701738  0.197516  0.585445   
3551  0.000000  0.631993  0.00  0.00  0.143842  0.620966  0.392916  0.712633   
212   0.166667  0.593932  0.15  0.00  0.268582  0.757144  0.127397  0.373846   
1036  0.133333  0.582594  0.00  0.00  0.210885  0.748941  0.184488  0.387687   
3629  0.333333  0.818425  0.30  0.50  0.206052  0.807365  0.086700  0.432402   
900   0.066700  0.572751  0.00  0.00  0.157317  0.734673  0.207167  0.558245   
3408  0.033300  0.507394  0.05  0.00  0.160217  0.732630  0.232861  0.544566   
3589  0.066700  0.619325  0.10  0.00  0.144298  0.644812  0.265187  0.521253   
741   0.133333  0.582364  0.00  0.00  0.630878  0.785149  0.146058  0.435212   
3294  0.066700  0.506409  0.00  0.00  0.171952  0.666280  0.311067  0.585445   
2903  0.266667  0.743941  0.15  0.00  0.410277  0.730910  0.156257  0.423773   
2018  0.266667  0.616139  0.00  0.00  0.634173  0.777794  0.195580  0.274064   
1206  0.133333  0.638926  0.00  0.25  0.186682  0.659501  0.321547  0.588011   
509   0.100000  0.586991  0.25  0.00  0.153868  0.604275  0.377847  0.559602   
597   0.033300  0.687997  0.00  0.00  0.240256  0.679617  0.305694  0.356814   
2688  0.066700  0.528219  0.00  0.00  0.187663  0.823706  0.182728  0.142724   
981   0.133333  0.589436  0.20  0.00  0.121040  0.708704  0.154505  0.476568   
3688  0.000000  0.457246  0.00  0.00  0.174821  0.634010  0.370388  0.532645   
3299  0.066700  0.594178  0.05  0.00  0.167116  0.606119  0.335673  0.575496   
518   0.100000  0.546864  0.00  0.00  0.192858  0.663377  0.313182  0.441263   
1902  0.000000  0.719994  0.20  0.00  0.136023  0.653065  0.320585  0.621740   
767   0.133333  0.664546  0.10  0.00  0.208142  0.804577  0.112989  0.396615   
2481  0.100000  0.572885  0.20  0.00  0.120293  0.709037  0.154519  0.465077   
...        ...       ...   ...   ...       ...       ...       ...       ...   
1184  0.066700  0.640995  0.10  0.00  0.342925  0.613487  0.273658  0.172276   
2324  0.100000  0.526644  0.15  0.00  0.162175  0.755419  0.159350  0.429780   
955   0.133333  0.598670  0.20  0.00  0.110352  0.731007  0.153058  0.519106   
1215  0.100000  0.810086  0.10  0.25  0.250873  0.715098  0.249590  0.394646   
2433  0.066700  0.554829  0.15  0.00  0.223554  0.717200  0.208444  0.067800   
2853  0.100000  0.604243  0.25  0.00  0.262299  0.595670  0.283829  0.477059   
3485  0.133333  0.572727  0.40  0.00  0.070500  0.695154  0.200023  0.525479   
1515  0.000000  0.543916  0.10  0.50  0.170298  0.695208  0.267011  0.485871   
2391  0.033300  0.506371  0.05  0.00  0.229578  0.557405  0.427767  0.585445   
769   0.100000  0.695394  0.10  0.25  0.251657  0.693362  0.279455  0.385767   
3380  0.066700  0.482771  0.00  0.00  0.391541  0.759624  0.224503  0.067800   
1685  0.200000  0.585755  0.00  0.00  0.120781  0.763128  0.269188  0.469070   
130   0.033300  0.436629  0.00  0.00  0.277219  0.787429  0.188418  0.076600   
2919  0.033300  0.561723  0.05  0.00  0.260921  0.627654  0.333850  0.299434   
3171  0.066700  0.599517  0.05  0.00  0.154127  0.659236  0.336056  0.605189   
3444  0.100000  0.632568  0.10  0.00  0.148115  0.648939  0.273706  0.488574   
2135  0.100000  0.706469  0.10  0.00  0.352069  0.630120  0.293848  0.071300   
1482  0.100000  0.523801  0.00  0.00  0.146938  0.775048  0.167330  0.310929   
330   0.0667

In [9]:
X_test

D1        D2    D3    D4        D5        D6        D7        D8  \
2148  0.100000  0.734427  0.20  0.25  0.136259  0.674081  0.212153  0.512164   
1044  0.000000  0.372990  0.00  0.00  0.124049  0.608342  0.405229  0.593604   
3319  0.000000  0.337305  0.00  0.00  0.192214  0.702996  0.281719  0.067800   
439   0.033300  0.560480  0.05  0.00  0.154026  0.616952  0.228655  0.528427   
3516  0.033300  0.694001  0.00  0.00  0.280807  0.574624  0.451219  0.705057   
1849  0.033300  0.574769  0.10  0.00  0.110869  0.621503  0.400619  0.582147   
93    0.033300  0.594765  0.00  0.00  0.282986  0.391600  0.568008  0.244860   
1281  0.066700  0.603841  0.10  0.00  0.363178  0.699844  0.210319  0.067800   
3578  0.200000  0.697912  0.10  0.25  0.111774  0.645036  0.321730  0.598010   
1272  0.200000  0.595613  0.00  0.00  0.595867  0.766210  0.188258  0.304016   
2981  0.133333  0.515541  0.00  0.00  0.178843  0.853353  0.129022  0.067800   
2937  0.000000  0.559351  0.05  0.00  0.141302  0.620285  0.402142  0.626908   
490   0.033300  0.614550  0.05  0.25  0.260872  0.649686  0.270175  0.421733   
3503  0.066700  0.623502  0.05  0.00  0.254455  0.632529  0.283413  0.526086   
544   0.033300  0.596548  0.05  0.00  0.146924  0.610086  0.377721  0.554260   
676   0.066700  0.596548  0.05  0.00  0.267811  0.697347  0.227905  0.497431   
1871  0.066700  0.506371  0.00  0.00  0.269964  0.861883  0.206706  0.085600   
2606  0.066700  0.635501  0.20  0.00  0.152517  0.608052  0.282294  0.585445   
3128  0.000000  0.650481  0.05  0.00  0.271098  0.656207  0.280582  0.501356   
1620  0.033300  0.436629  0.00  0.00  0.105118  0.605757  0.407355  0.588199   
564   0.000000  0.510304  0.10  0.00  0.145615  0.666486  0.288214  0.552029   
3331  0.200000  0.560006  0.00  0.00  0.114402  0.827550  0.221584  0.542500   
1161  0.100000  0.616214  0.10  0.25  0.098000  0.731087  0.153044  0.513779   
3300  0.500000  0.559221  0.10  0.00  0.226491  0.829160  0.102634  0.067800   
414   0.133333  0.633541  0.10  0.00  0.455650  0.742363  0.162059  0.339588   
3260  0.000000  0.389543  0.00  0.00  0.167227  0.633717  0.352000  0.540116   
1545  0.066700  0.493893  0.00  0.00  0.278212  0.849841  0.285377  0.079100   
712   0.000000  0.433635  0.00  0.00  0.108811  0.636028  0.416499  0.593737   
3530  0.000000  0.719994  0.20  0.00  0.133844  0.653030  0.320585  0.631525   
1915  0.133333  0.685359  0.15  0.00  0.214087  0.692414  0.179712  0.462112   
...        ...       ...   ...   ...       ...       ...       ...       ...   
2522  0.066700  0.565921  0.15  0.00  0.121796  0.640700  0.297472  0.494664   
1778  0.000000  0.712450  0.10  0.00  0.319590  0.669435  0.351028  0.285991   
2579  0.066700  0.548721  0.00  0.00  0.230967  0.693012  0.260372  0.584973   
3609  0.033300  0.614471  0.10  0.00  0.208383  0.625490  0.224363  0.515688   
2111  0.033300  0.593906  0.00  0.00  0.247057  0.608563  0.370411  0.474001   
3372  0.066700  0.497448  0.00  0.00  0.147541  0.722517  0.212568  0.550544   
2611  0.000000  0.384301  0.00  0.00  0.127185  0.615922  0.378336  0.564015   
1444  0.300000  0.556521  0.00  0.00  0.090000  0.875568  0.103631  0.411653   
3580  0.133333  0.598443  0.00  0.00  0.159568  0.732045  0.209757  0.585445   
1143  0.000000  0.622021  0.05  0.00  0.239621  0.569136  0.305656  0.634186   
3337  0.066700  0.598670  0.10  0.00  0.190488  0.624753  0.297858  0.479177   
191   0.033300  0.438899  0.05  0.00  0.114438  0.605509  0.405013  0.625881   
104   0.033300  0.617678  0.05  0.00  0.131924  0.593993  0.432915  0.599369   
2778  0.066700  0.538682  0.05  0.00  0.319676  0.726682  0.158925  0.269955   
1642  0.066700  0.630876  0.10  0.00  0.188646  0.768299  0.243188  0.415038   
1499  0.066700  0.528219  0.00  0.00  0.155302  0.771648  0.246465  0.228751   
3598  0.100000  0.645393  0.20  0.00  0.160496  0.616361  0.295003  0.491456   
1456  0.033300  0.443543  0.00  0.00  0.251796  0.728015  0.238594  0.183972   
1450  0.0667

In [10]:
y_train

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

In [11]:
y_test

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
model = LogisticRegression()
model.fit(X_train, y_train)
preds = model.predict(X_test)

In [14]:
preds

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [15]:
type(preds)

numpy.ndarray

In [16]:
from sklearn.metrics import accuracy_score

print(accuracy_score(preds, y_test))

0.75605815832


In [17]:
from sklearn.model_selection import cross_val_score

print(cross_val_score(model, X_train, y_train, cv=5))

[ 0.74404762  0.73956262  0.72310757  0.75099602  0.75896414]


In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [19]:
%%time

models = [
    KNeighborsClassifier(),
    DecisionTreeClassifier(),
    LinearSVC(),
    RandomForestClassifier(n_estimators=100), 
    GradientBoostingClassifier(n_estimators=100)
]

for model in models:
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    print(accuracy_score(preds, y_test), model)

0.718901453958 KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
0.712439418417 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
0.739903069467 LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
0.78352180937 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
  

In [20]:
from sklearn import cross_validation, datasets, grid_search, linear_model, metrics

C:\Users\DimaN228\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\DimaN228\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [21]:
from sklearn.cross_validation import KFold

cv = KFold(len(X_train), n_folds=5)

In [24]:
cv

sklearn.cross_validation.KFold(n=2513, n_folds=5, shuffle=False, random_state=None)

In [25]:
from sklearn.grid_search import GridSearchCV

In [64]:
from sklearn.grid_search import RandomizedSearchCV

In [66]:
from sklearn.model_selection import GridSearchCV, cross_val_score

In [67]:
tree_params = {'max_depth': range(1,11),
'max_features': range(4,19)}

In [70]:
tree = DecisionTreeClassifier(max_depth=5, random_state=17)

In [71]:
tree_grid = GridSearchCV(tree, tree_params,
cv=5, n_jobs=-1,
verbose=True)

In [72]:
tree_grid.fit(X_train, y_train)

Fitting 5 folds for each of 150 candidates, totalling 750 fits


[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  1.3min
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done 750 out of 750 | elapsed:  2.1min finished


GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=17,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'max_depth': range(1, 11), 'max_features': range(4, 19)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=True)

In [74]:
tree_grid.best_params_

{'max_depth': 9, 'max_features': 17}

In [75]:
tree_grid.best_score_

0.6812574612017509

In [76]:
from sklearn.ensemble import RandomForestClassifier

In [77]:
forest_params = {'max_depth': range(1,11),
'max_features': range(4,19)}

In [78]:
forest = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=17)

In [79]:
forest_grid = GridSearchCV(forest, forest_params,
cv=5, n_jobs=-1,
verbose=True)

In [80]:
forest_grid.fit(X_train, y_train)

Fitting 5 folds for each of 150 candidates, totalling 750 fits


[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   19.8s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   55.0s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-1)]: Done 750 out of 750 | elapsed:  3.6min finished


GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=17, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'max_depth': range(1, 11), 'max_features': range(4, 19)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=True)

In [81]:
print(forest_grid.best_score_)
print(forest_grid.best_estimator_)

0.771985674493
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features=18, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=17, verbose=0, warm_start=False)


In [82]:
print(forest_grid.best_score_)

0.771985674493


In [83]:
tree_grid = RandomizedSearchCV(tree, tree_params,
cv=5, n_jobs=-1,
verbose=True)
tree_grid.fit(X_train, y_train)
print(tree_grid.best_score_)
print(tree_grid.best_estimator_)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   29.1s


0.6573816155988857
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=7,
            max_features=18, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=17,
            splitter='best')


[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:   29.8s finished


In [84]:
forest_grid = RandomizedSearchCV(forest, forest_params,
cv=5, n_jobs=-1,
verbose=True)
forest_grid.fit(X_train, y_train)
print(forest_grid.best_score_)
print(forest_grid.best_estimator_)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   15.4s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:   17.5s finished


0.7684042976522085
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features=15, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=17, verbose=0, warm_start=False)


Эффективным оказался по времени RandomizedSearchCV